FROM python:3.11-slim

WORKDIR /app

# Install dependencies (We re-use the same cache)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy code
COPY . .

# Streamlit runs on 8501
EXPOSE 8501

# The HEALTHCHECK ensures the container is actually ready
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health || exit 1

CMD ["streamlit", "run", "app_client.py", "--server.port=8501", "--server.address=0.0.0.0"]